# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from etudiants import Ui_Dialog as EtudiantsDialog
from filieres import Ui_Dialog as FilieresDialog

def create_database():
    conn = sqlite3.connect("school.db")
    cursor = conn.cursor()

    cursor.execute('''CREATE TABLE IF NOT EXISTS filieres (
                        id INTEGER PRIMARY KEY AUTOINCREMENT, 
                        name TEXT)''')

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS etudiants (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        email TEXT,
        classe_id INTEGER,
        FOREIGN KEY (classe_id) REFERENCES filieres(id) ON DELETE CASCADE
    )
    """)

    conn.commit()
    conn.close()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color : #FBF6E9;   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.btnEtudiant = QtWidgets.QPushButton(self.centralwidget)
        self.btnEtudiant.setGeometry(QtCore.QRect(190, 310, 171, 61))
        self.btnEtudiant.setStyleSheet("background-color: #118B50;\n"
                                       "color: white;\n"
                                       "border-radius: 8px;\n"
                                       "padding: 8px 16px;\n"
                                       "")
        self.btnEtudiant.setObjectName("btnEtudiant")
        
        self.btnFiliere = QtWidgets.QPushButton(self.centralwidget)
        self.btnFiliere.setGeometry(QtCore.QRect(430, 310, 171, 61))
        self.btnFiliere.setStyleSheet("background-color: #118B50;\n"
                                      "color: white;\n"
                                      "border-radius: 8px;\n"
                                      "padding: 8px 16px;")
        self.btnFiliere.setObjectName("btnFiliere")
        
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(140, 130, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAcceptDrops(False)
        self.label1.setStyleSheet("background-color : #FBF6E9;\n"
                                  "color: #5DB996;")
        self.label1.setObjectName("label1")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setStyleSheet("background-color : #FBF6E9; \n"
                                   "color : #118B50;")
        self.menuBar.setObjectName("menuBar")

        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setStyleSheet("background-color : #FBF6E9; ")
        
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.actionGererEtudiants = QtWidgets.QAction("Gérer les Étudiants", MainWindow)
        self.actionGererEtudiants.setObjectName("actionGererEtudiants")

        self.actionGererFilieres = QtWidgets.QAction("Gérer les Filières", MainWindow)
        self.actionGererFilieres.setObjectName("actionGererFilieres")

        self.menu.addAction(self.actionGererEtudiants)
        self.menu.addAction(self.actionGererFilieres)

        self.actionGererEtudiants.triggered.connect(self.open_etudiants_window)
        self.actionGererFilieres.triggered.connect(self.open_filieres_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnEtudiant.clicked.connect(self.open_etudiants_window)
        self.btnFiliere.clicked.connect(self.open_filieres_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnEtudiant.setText(_translate("MainWindow", "Gérer les étudiants"))
        self.btnFiliere.setText(_translate("MainWindow", "Gérer les filières"))
        self.label1.setText(_translate("MainWindow", "Application de gestion de scolarité"))
        self.menu.setTitle(_translate("MainWindow", "Gestion"))
    
    def open_etudiants_window(self):
        self.window = QtWidgets.QDialog()
        self.ui = EtudiantsDialog()
        self.ui.setupUi(self.window)
        self.window.exec_()

    def open_filieres_window(self):
        self.window = QtWidgets.QDialog()
        self.ui = FilieresDialog()
        self.ui.setupUi(self.window)
        self.window.exec_()

if __name__ == "__main__":
    import sys
    create_database()

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
